"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-29

Creates every table from app.models in one shot via metadata.create_all,
rather than hand-writing ~15 op.create_table() calls that could drift from
the SQLAlchemy models. Later schema changes should be normal autogenerated
Alembic revisions on top of this baseline.
"""

from alembic import op

import app.models  # noqa: F401 - populates Base.metadata
from app.core.database import Base

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
