"""FBX -> GLB conversion, against FBX files generated by Blender with known
geometry (no binary fixtures committed). Skipped where Blender isn't installed."""

import subprocess
import textwrap
from pathlib import Path

import pytest

from app.services.model3d.fbx_convert import FbxConversionError, convert_fbx_to_glb, find_blender
from app.services.model3d.glb_inspect import compute_glb_bounds, compute_scale_for_real_height

BLENDER = find_blender(None)
pytestmark = pytest.mark.skipif(BLENDER is None, reason="Blender not installed")

# Box 0.1m wide (X), 0.2m deep (Y), 0.3m tall (Z-up in Blender), resting on the
# ground and offset from the origin; both via a unit_scale and an object
# transform, so conversion has to handle units AND unapplied transforms.
_MAKE_FBX = textwrap.dedent(
    """
    import sys, bpy
    out, unit = sys.argv[sys.argv.index("--") + 1:]
    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    if unit == "cm":
        scene.unit_settings.scale_length = 0.01
        k = 100.0
    else:
        k = 1.0
    bpy.ops.mesh.primitive_cube_add(size=1.0)
    box = bpy.context.active_object
    box.scale = (0.1 * k, 0.2 * k, 0.3 * k)          # left unapplied on purpose
    box.location = (0.5 * k, 0.0, 0.15 * k)
    if unit != "empty":
        bpy.ops.export_scene.fbx(filepath=out)
    else:
        bpy.ops.object.delete()
        bpy.ops.object.empty_add()
        bpy.ops.export_scene.fbx(filepath=out)
    """
)


def _make_fbx(tmp_path: Path, unit: str) -> bytes:
    script = tmp_path / "make_fbx.py"
    script.write_text(_MAKE_FBX)
    out = tmp_path / f"box_{unit}.fbx"
    subprocess.run(
        [str(BLENDER), "-b", "--factory-startup", "--python", str(script), "--", str(out), unit],
        check=True,
        capture_output=True,
        timeout=180,
    )
    return out.read_bytes()


def _extents(glb: bytes) -> tuple[float, float, float]:
    bounds = compute_glb_bounds(glb)
    return tuple(hi - lo for lo, hi in zip(bounds.min, bounds.max))


@pytest.mark.parametrize("unit", ["m", "cm"])
def test_fbx_converts_to_real_size_glb_with_y_up(tmp_path, unit):
    glb = convert_fbx_to_glb(_make_fbx(tmp_path, unit), None)
    assert glb[:4] == b"glTF"
    width, height, depth = _extents(glb)
    # Blender Z-up height becomes glTF Y-up height; units come out in meters.
    assert width == pytest.approx(0.1, rel=1e-3)
    assert height == pytest.approx(0.3, rel=1e-3)
    assert depth == pytest.approx(0.2, rel=1e-3)


def test_converted_glb_scale_for_real_height(tmp_path):
    glb = convert_fbx_to_glb(_make_fbx(tmp_path, "cm"), None)
    # Already in meters, so asking for its true height needs no correction.
    assert compute_scale_for_real_height(glb, 0.3) == pytest.approx(1.0, rel=1e-3)


def test_fbx_without_mesh_is_rejected(tmp_path):
    with pytest.raises(FbxConversionError, match="no mesh"):
        convert_fbx_to_glb(_make_fbx(tmp_path, "empty"), None)


def test_garbage_bytes_are_rejected(tmp_path):
    with pytest.raises(FbxConversionError):
        convert_fbx_to_glb(b"not an fbx file at all", None)
